# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cb78556c926ea6bf08e19cbf31aca8d7e287b4d019a430d12ec9d34f9334e12686e990ca1491e9739d6ff8fa170e57ca976b8e95c0a23671d21d57115f35b70

test:
  secret_key_base: 9c7fb57fc5432a3d33c40e6f8b17364a84793ae3ac5f4d42c525a00cf2f8cd7d848a78dc1c50d2da35c12febf80a34b12fc0af51b3f60979773c4e2da4b1b894

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
